id: P010643
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:17:52.252512
source_metadata:
  id: bdr:W1KG4463
  title: རྩ་བ་ཤེས་རབ་ཀྱི་དཀའ་གནས་ཆེན་པོ་བརྒྱད་ཀྱི་བཤད་པ་
  author: ''
  volumes:
    73fec4cbf20a4b74917e51110c591bef:
      image_group_id: I1KG4481
      title: ''
      volume_number: 1
      total_pages: 64
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
