id: IA534AA7E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:34:49+00:00'
last_modified: '2022-06-08T16:27:43.670461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4463
  title: རྩ་བ་ཤེས་རབ་ཀྱི་དཀའ་གནས་ཆེན་པོ་བརྒྱད་ཀྱི་བཤད་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FFBA:
      image_group_id: I1KG4481
      title: ''
      total_pages: 64
      order: 1
      base_file: FFBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
