id: IA534AA7E
legacy_id: P010643
ocr_import_info:
  bdrc_scan_id: W1KG4463
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T18:34:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:41:19.697408+00:00'
last_modified: 2022-09-01 00:41:24.888573
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4463
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4463
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩ་བ་ཤེས་རབ་ཀྱི་དཀའ་གནས་ཆེན་པོ་བརྒྱད་ཀྱི་བཤད་པ།
  author: རྒྱལ་ཚབ་དར་མ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.8007149721666393
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1KG4481:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4481
      total_pages: 64
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4481.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8007149721666393
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
